import localFont from 'next/font/local'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/app/components/SessionProvider.js'
import NavMenu from './components/NavMenu.js'
import { HabiticaProvider } from './context/habiticaAuth.js'

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--font-geist-sans',
   weight: '100 900',
})
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--font-geist-mono',
   weight: '100 900',
})

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
   const session = await getServerSession()
   return (
      <html lang="en">
         <SessionProvider session={session}>
            <HabiticaProvider>
               <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  <NavMenu />
                  {children}
               </body>
            </HabiticaProvider>
         </SessionProvider>
      </html>
   )
}
